'use strict';

export const NAVIGATE_PROJECTS = 'NAVIGATE_PROJECTS';
export const ENTER_PROJECT = 'ENTER_PROJECTS';
export const SHOW_PROJECT = 'SHOW_PROJECT';
export const GET_PROJECTS = 'GET_PROJECTS';
export const SHOW_CATEGORY = 'SHOW_CATEGORY';
export const CLEAR_CATEGORY = 'CLEAR_CATEGORY';
export const UPDATE_PROJECT_MOUSE = 'UPDATE_PROJECT_MOUSE';
