contentColumnType: string
fieldGroup: 3a27efe0-652c-4a93-afc7-755455810a60
handle: projectLayers
instructions: ''
name: 'Project Layers'
searchable: true
settings:
  contentTable: '{{%matrixcontent_projectlayers}}'
  localizeBlocks: false
  maxBlocks: ''
  minBlocks: ''
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
