enableVersioning: true
handle: projects
name: Projects
previewTargets:
  -
    label: 'Primary entry page'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  1ca609a1-4ff3-4e3c-9780-72a3e090292b:
    enabledByDefault: true
    hasUrls: true
    template: index
    uriFormat: 'projects/{slug}'
structure:
  maxLevels: 1
  uid: 689e7abf-4fa6-43a2-b14e-1fcb7529f2e0
type: structure
